[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/2023-03-13-soutenir-le-numerique-social-et-solidaire-le-trou-dans-la-raquette-quil-faut-combler-avant-2030/index.html"
to = "/revue-de-presse/2022-11-29-soutenir-le-numerique-social-et-solidaire-le-trou-dans-la-raquette-quil-faut-combler-avant-2030/"

[[redirects]]
from = "/actualites/index.html"
to = "/revue-de-presse/"

[[redirects]]
from = "/revue-de-presse/2023-03-13-soutenir-le-numerique-social-et-solidaire-le-trou-dans-la-raquette-quil-faut-combler-avant-2030/index.html"
to = "/revue-de-presse/2022-11-29-soutenir-le-numerique-social-et-solidaire-le-trou-dans-la-raquette-quil-faut-combler-avant-2030/"

